-- ENUM types
create type channel_kind as enum ('ai', 'snow');
create type source_type_kind as enum ('rss', 'email');
create type lang_kind as enum ('zh_CN', 'en');

-- 1. news_items
create table news_items (
  id bigint generated by default as identity primary key,
  channel channel_kind not null,
  source_type source_type_kind not null,
  source text not null,
  title text not null,
  content text,
  link text,
  link_canonical text,
  pub_date timestamptz,
  external_id text,
  dedup_key text not null generated always as (
    coalesce(external_id, link_canonical, md5(coalesce(title,'') || coalesce(content,'')))
  ) stored,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  compressed boolean not null default false,
  attempt_count int not null default 0,
  last_error text,
  claimed_at timestamptz,
  claim_id uuid,
  unique (channel, source, dedup_key)
);
create index news_items_pending on news_items (channel, fetched_at)
  where compressed = false and attempt_count < 5;

-- 2. drafts
create table drafts (
  id bigint generated by default as identity primary key,
  channel channel_kind not null,
  content text not null,
  source_item_ids bigint[] not null,
  scored boolean not null default false,
  attempt_count int not null default 0,
  last_error text,
  claimed_at timestamptz,
  claim_id uuid,
  created_at timestamptz not null default now()
);
create index drafts_pending on drafts (channel, created_at)
  where scored = false and attempt_count < 5;

-- 3. scored_drafts
create table scored_drafts (
  id bigint generated by default as identity primary key,
  channel channel_kind not null,
  draft_id bigint not null references drafts(id),
  content text not null,
  merged boolean not null default false,
  published boolean not null default false,
  attempt_count int not null default 0,
  last_error text,
  claimed_at timestamptz,
  claim_id uuid,
  created_at timestamptz not null default now()
);
create index scored_drafts_pending on scored_drafts (channel, created_at)
  where merged = false and attempt_count < 5;
create index scored_drafts_recent_published on scored_drafts (channel, created_at)
  where published = true;

-- 4. pre_publish
create table pre_publish (
  id bigint generated by default as identity primary key,
  channel channel_kind not null,
  title text not null,
  summary text,
  content_md text not null,
  content_html text,
  tags text[] not null default '{}',
  cover_image text,
  source_scored_ids bigint[] not null,
  published boolean not null default false,
  published_journal_id bigint,
  attempt_count int not null default 0,
  last_error text,
  claimed_at timestamptz,
  claim_id uuid,
  created_at timestamptz not null default now()
);
create index pre_publish_pending_render on pre_publish (channel, created_at)
  where content_html is null and attempt_count < 5;
create index pre_publish_pending_publish on pre_publish (channel, created_at)
  where content_html is not null and published = false and attempt_count < 5;

-- 5. issues
create table issues (
  id bigint generated by default as identity primary key,
  channel channel_kind not null,
  lang lang_kind not null default 'zh_CN',
  title text not null,
  summary text,
  content_html text not null,
  tags text[] not null default '{}',
  cover_image text,
  journal_id bigint,
  pre_publish_id bigint references pre_publish(id),
  delivering_at timestamptz,
  delivered boolean not null default false,
  delivered_at timestamptz,
  delivery_attempt_count int not null default 0,
  delivery_last_error text,
  created_at timestamptz not null default now(),
  published_at timestamptz not null default now()
);
create index issues_published on issues (channel, lang, published_at desc);
create index issues_pending_deliver on issues (channel, published_at)
  where delivered = false;

-- 6. cover_images
create table cover_images (
  id bigint generated by default as identity primary key,
  channel channel_kind not null,
  description text,
  image_url text not null,
  link text,
  source text,
  used_count int not null default 0,
  created_at timestamptz not null default now()
);
create index cover_images_lru on cover_images (channel, used_count, created_at);

-- 7. tag_counts
create table tag_counts (
  channel channel_kind not null,
  lang lang_kind not null,
  name text not null,
  total bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (channel, lang, name)
);
