-- Enable pgvector extension (Supabase has it available, just needs activation).
create extension if not exists vector with schema extensions;

create table event_embeddings (
  id            bigint generated by default as identity primary key,
  channel       channel_kind not null,
  pre_publish_id bigint not null references pre_publish(id) on delete cascade,
  title         text not null,
  description   text not null default '',
  embedding     vector(3072) not null,
  created_at    timestamptz not null default now()
);

create index event_embeddings_channel_created
  on event_embeddings (channel, created_at desc);

-- pgvector HNSW/IVFFlat indexes cap at 2000 dims; gemini-embedding-001
-- outputs 3072. With <1000 rows in the 72h dedup window, sequential scan
-- is trivially fast — no vector index needed at this scale.

-- RLS: pipeline uses service_role_key so RLS is bypassed, but add a
-- permissive select policy for the anon key (frontend read-only).
alter table event_embeddings enable row level security;
create policy "anon_select_event_embeddings"
  on event_embeddings for select to anon using (true);
