create table llm_usage (
  id            bigint generated by default as identity primary key,
  channel       channel_kind not null,
  step          text not null,
  provider      text not null,
  model         text not null,
  input_tokens  int not null default 0,
  output_tokens int not null default 0,
  cost_usd      numeric(10, 6) not null default 0,
  duration_ms   int,
  created_at    timestamptz not null default now()
);

create index llm_usage_channel_created
  on llm_usage (channel, created_at desc);

alter table llm_usage enable row level security;
create policy "anon_select_llm_usage"
  on llm_usage for select to anon using (true);
