// scripts/publish-ibm-cobol-en-v5.2.js
const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = "https://ylcjjcfopcuwtspiiytl.supabase.co";
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || "SUPABASE_SERVICE_ROLE_KEY_REDACTED_ROTATED_2026_02";

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

const articleTitle = "Ghosts of the Nixon Era and IBM's Death Sentence: How Claude Code Dismantles a Trillion-Dollar Moat";
const articleSlug = "ghosts-nixon-era-ibm-death-sentence";
const articleExcerpt = "Anthropic is physically liquidating IBM's core assets via Claude Code. When AI flattens the 'cost barrier' of understanding legacy code, the inefficient arbitrage model of traditional IT consulting goes bankrupt.";

const articleBody = `
# Ghosts of the Nixon Era and IBM's Death Sentence: How Claude Code Dismantles a Trillion-Dollar Moat

**Core Dynamics**
*   IBM shares reel from the direct impact of Anthropic’s blog, signaling a violent shift in market expectations regarding traditional IT service moats.
*   COBOL Reality: Processes 95% of US ATM transactions, with hundreds of billions of lines running daily in a "no author, no docs, no replacement" black-box state.
*   The Equation: Claude Code automates dependency mapping and logical reverse engineering, compressing COBOL modernization cycles from years to quarters.

IBM’s deepest moat was never technical superiority; it was the "cost of understanding" legacy systems.

This model is as secretive as it is lucrative: trillions of lines of COBOL code built during the Nixon administration serve as the bedrock for global finance and government. The cost of understanding this code is higher than the cost of rewriting it, allowing consulting giants like IBM to sell human man-hours for decades to maintain bloated balance sheets. Anthropic’s latest disclosure serves as a death warrant for this labor arbitrage.

![IBM Stock Crash](/images/blog/cobol-death-ibm-moat/ibm-stock-crash.jpg)

From a financial modeling perspective, when Claude Code automatically maps implicit dependencies across hundreds of files, the "Discovery phase"—the largest chunk of traditional consulting revenue—instantly vanishes. This means IBM’s backlog of over $60 billion in services is effectively devalued. The market sell-off reveals a brutal truth: any moat built on closed ecosystems and manufactured complexity holds zero defensive value against AI. This isn't evolution; it's a physical liquidation of the IT consulting industry.

// Dissent:

This optimism, equating "code translation" with "system reconstruction," completely ignores the staggering physical overhead of long-context reasoning.

Automating the mapping of COBOL’s shared data structures and global states requires models to maintain work memory (KV Cache) for millions of tokens in System 2 mode. In the face of spaghetti code modified repeatedly over decades, H100’s 3.3 TB/s memory bandwidth becomes a fatal bottleneck for real-time dependency tracking. When a model attempts to reverse-engineer complex financial settlement logic, error accumulation in long-range reasoning will lead to high failure rates.

Data from a16z’s TetrisBench proves that model success rates for out-of-distribution (OOD) chaotic systems lag significantly behind marketing benchmarks. Your "modernization in a few quarters" comes at the price of massive power consumption across compute clusters and the violent exhaustion of HBM3e bandwidth.

IBM’s mercenaries may be aging, but the "computational debt" generated by processing these Nixon-era ghosts will be the next great cash flow black hole.

The essence of this war is not the migration of code, but the transfer of inefficient human labor to extremely expensive silicon compute. Traditional IT consulting is slated for execution, but the AI titans taking over will feel the cold sting of physical entropy as they attempt to swallow decades of accumulated logical chaos.
`;

const coverImageUrl = "/images/blog/cobol-death-ibm-moat/cover.png";

async function publish() {
  console.log(`🚀 Publishing English Version: ${articleTitle}`);
  
  const { data: existing } = await supabase
    .from('snapai_insights')
    .select('id')
    .eq('slug', articleSlug)
    .single();

  let result;
  if (existing) {
    console.log(`🔄 Updating existing article ID: ${existing.id}`);
    result = await supabase
      .from('snapai_insights')
      .update({
        title: articleTitle,
        excerpt: articleExcerpt,
        content_md: articleBody,
        cover_image: coverImageUrl,
        tags: ['Anthropic', 'IBM', 'COBOL', 'Claude Code'],
        author: 'Brad',
        related_journal_id: '416',
        lang: 'en',
        is_published: true,
        updated_at: new Date().toISOString()
      })
      .eq('id', existing.id);
  } else {
    console.log(`🆕 Inserting new article`);
    result = await supabase
      .from('snapai_insights')
      .insert({
        title: articleTitle,
        slug: articleSlug,
        excerpt: articleExcerpt,
        content_md: articleBody,
        cover_image: coverImageUrl,
        tags: ['Anthropic', 'IBM', 'COBOL', 'Claude Code'],
        author: 'Brad',
        related_journal_id: '416',
        lang: 'en',
        is_published: true
      });
  }

  if (result.error) {
    console.error('❌ Failed:', result.error);
  } else {
    console.log('✅ Success!');
  }
}

publish();
